version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000 #host port:container port

  backend:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/vidly   #vidly is db name .to define where our database is.
  
  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db  # to make sure it doesn't store database data inside temporary folder .Instead a defined folder

volumes: #it's syntax rule.We have to define volume first 
  vidly: 